sudo: false

notifications:
    email: false

language: python

python:
  - "3.5"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
    - pip install coverage
    - pip install https://github.com/tariqdaouda/rabaDB/archive/stable.zip
    - python setup.py install

script: coverage run -m unittest discover pyGeno/tests/

after_success: bash <(curl -s https://codecov.io/bash)
